=== yasminshaik23/Wipro-TalentNext/XML/Project/Exercises/Exercise9_Catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalog">

        <xs:complexType>

            <xs:sequence>

                <xs:element name="product">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="catalog_item" maxOccurs="unbounded">

                                <xs:complexType>

                                    <xs:sequence>

                                        <xs:element name="item_number" type="xs:string"/>

                                        <xs:element name="price" type="xs:decimal"/>

                                        <xs:element name="size" maxOccurs="unbounded">

                                            <xs:complexType>

                                                <xs:sequence>

                                                    <xs:element name="color_swatch" maxOccurs="unbounded">

                                                        <xs:complexType mixed="true">

                                                            <xs:attribute name="image"
                                                                type="xs:string"
                                                                use="required"/>
                                                        </xs:complexType>

                                                    </xs:element>

                                                </xs:sequence>

                                                <xs:attribute name="description"
                                                    type="xs:string"
                                                    use="required"/>

                                            </xs:complexType>

                                        </xs:element>

                                    </xs:sequence>

                                    <xs:attribute name="gender"
                                        type="xs:string"
                                        use="required"/>

                                </xs:complexType>

                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="description"
                            type="xs:string"
                            use="required"/>

                        <xs:attribute name="product_image"
                            type="xs:string"
                            use="required"/>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>

=== yasminshaik23/Wipro-TalentNext/XML/Project/Exercises/Exercise4_Catalog.xml
<?xml version="1.0"?>

<?xml-stylesheet href="catalog.xsl" type="text/xsl"?>


<catalog
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Exercise9_Catalog.xsd">

    <product description="Cardigan Sweater" product_image="cardigan.jpg">

        <catalog_item gender="Men's">

            <item_number>QWZ5671</item_number>

            <price>39.95</price>

            <size description="Medium">
                <color_swatch image="red_cardigan.jpg">Red</color_swatch>
                <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
            </size>

            <size description="Large">
                <color_swatch image="red_cardigan.jpg">Red</color_swatch>
                <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
            </size>

        </catalog_item>

        <catalog_item gender="Women's">

            <item_number>RRX9856</item_number>

            <price>42.50</price>

            <size description="Small">
                <color_swatch image="red_cardigan.jpg">Red</color_swatch>
                <color_swatch image="navy_cardigan.jpg">Navy</color_swatch>
                <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
            </size>

            <size description="Medium">
                <color_swatch image="red_cardigan.jpg">Red</color_swatch>
                <color_swatch image="navy_cardigan.jpg">Navy</color_swatch>
                <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
                <color_swatch image="black_cardigan.jpg">Black</color_swatch>
            </size>

            <size description="Large">
                <color_swatch image="navy_cardigan.jpg">Navy</color_swatch>
                <color_swatch image="black_cardigan.jpg">Black</color_swatch>
            </size>

            <size description="Extra Large">
                <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
                <color_swatch image="black_cardigan.jpg">Black</color_swatch>
            </size>

        </catalog_item>

    </product>

</catalog>
